FROM node:alpine as BUILDER
WORKDIR '/app'
COPY ./package.json ./
RUN npm install
COPY ./ ./
#CMD ["npm","start","build"]
RUN npm run build

FROM nginx:alpine as STARTER
COPY --from=BUILDER /app/build /usr/share/nginx/html





